"""
Data Management and Pipeline Engine
Pandas DataFrame conversions, export/import utilities (CSV, JSON, Markdown), and session tracking.
"""

import json
import pandas as pd
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone


def cards_to_dataframe(cards: List[Dict[str, Any]]) -> pd.DataFrame:
    """
    Transforms flashcard dictionary list into a structured Pandas DataFrame.
    """
    if not cards:
        return pd.DataFrame(columns=[
            "id", "front", "back", "tag", "repetition_count", 
            "ease_factor", "interval_days", "next_review", "mastery_score"
        ])
    
    df = pd.DataFrame(cards)
    # Ensure all required columns exist
    defaults = {
        "tag": "General",
        "repetition_count": 0,
        "ease_factor": 2.5,
        "interval_days": 1,
        "mastery_score": 0.0,
        "total_reviews": 0,
        "lapse_count": 0
    }
    for col, default_val in defaults.items():
        if col not in df.columns:
            df[col] = default_val

    # Reorder columns for clean presentation in st.data_editor
    ordered_cols = [
        "id", "front", "back", "tag", "mastery_score", 
        "repetition_count", "ease_factor", "interval_days", "next_review"
    ]
    actual_cols = [c for c in ordered_cols if c in df.columns] + [c for c in df.columns if c not in ordered_cols]
    return df[actual_cols]


def dataframe_to_cards(df: pd.DataFrame) -> List[Dict[str, Any]]:
    """
    Converts edited Pandas DataFrame back into a clean list of flashcard dictionaries.
    """
    if df.empty:
        return []
    records = df.to_dict(orient="records")
    clean_cards = []
    for r in records:
        clean_cards.append({
            "id": str(r.get("id", f"fc-{len(clean_cards) + 1}")),
            "front": str(r.get("front", "")),
            "back": str(r.get("back", "")),
            "tag": str(r.get("tag", "General")),
            "repetition_count": int(r.get("repetition_count", 0)),
            "ease_factor": float(r.get("ease_factor", 2.5)),
            "interval_days": int(r.get("interval_days", 1)),
            "next_review": str(r.get("next_review", "")),
            "last_reviewed": r.get("last_reviewed"),
            "mastery_score": float(r.get("mastery_score", 0.0)),
            "total_reviews": int(r.get("total_reviews", 0)),
            "lapse_count": int(r.get("lapse_count", 0))
        })
    return clean_cards


def quizzes_to_dataframe(quizzes: List[Dict[str, Any]]) -> pd.DataFrame:
    """
    Transforms quiz question list into a structured Pandas DataFrame.
    """
    if not quizzes:
        return pd.DataFrame(columns=["id", "type", "question", "answer", "explanation"])
    
    rows = []
    for q in quizzes:
        rows.append({
            "id": q.get("id", ""),
            "type": q.get("type", "mcq"),
            "question": q.get("question", ""),
            "answer": q.get("answer", ""),
            "options": ", ".join(q.get("options", [])) if isinstance(q.get("options"), list) else str(q.get("options", "")),
            "explanation": q.get("explanation", "")
        })
    return pd.DataFrame(rows)


def export_study_kit_to_json(kit: Dict[str, Any]) -> str:
    """
    Serializes complete study kit to a formatted JSON string.
    """
    return json.dumps(kit, indent=2, ensure_ascii=False)


def export_flashcards_to_csv(cards: List[Dict[str, Any]]) -> str:
    """
    Exports flashcards as CSV text (compatible with Anki and Quizlet).
    """
    df = cards_to_dataframe(cards)
    return df[["front", "back", "tag", "mastery_score"]].to_csv(index=False)


def export_study_guide_markdown(kit: Dict[str, Any]) -> str:
    """
    Generates a printable Markdown Study Guide and summary sheet.
    """
    topic = kit.get("topic", "Study Guide")
    summary = kit.get("executive_summary", "")
    concepts = kit.get("key_concepts", [])
    cards = kit.get("flashcards", [])
    quizzes = kit.get("quizzes", [])

    lines = [
        f"# 📚 {topic} - Comprehensive Study Guide",
        f"*Generated by StudyIQ AI Cognitive Engine • {datetime.now().strftime('%Y-%m-%d')}*",
        "",
        "## 💡 Executive Summary",
        summary or "No summary available.",
        "",
        "## 🔑 Core Concepts",
    ]
    for c in concepts:
        lines.append(f"- **{c}**")
    
    lines.extend(["", "---", "", "## 🗂️ Active Recall Flashcards", ""])
    for i, card in enumerate(cards, 1):
        lines.append(f"### Card {i} [{card.get('tag', 'Concept')}]")
        lines.append(f"**Q:** {card.get('front')}")
        lines.append(f"**A:** {card.get('back')}")
        lines.append("")

    lines.extend(["---", "", "## 🎯 Self-Assessment Quizzes", ""])
    for i, q in enumerate(quizzes, 1):
        lines.append(f"### Question {i} ({q.get('type', 'mcq').upper()})")
        lines.append(f"**Question:** {q.get('question')}")
        if q.get("options") and isinstance(q.get("options"), list):
            for opt in q["options"]:
                lines.append(f"  - {opt}")
        lines.append(f"**Answer:** `{q.get('answer')}`")
        lines.append(f"**Explanation:** *{q.get('explanation')}*")
        lines.append("")

    return "\n".join(lines)
